services:
  db:
    image: postgres:17
    container_name: storywink_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shaunyas
      POSTGRES_DB: storywink
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - SW_NETWORK
  redis:
    image: redis:7-alpine
    container_name: storywink_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - SW_NETWORK

volumes:
  postgres_data:
  redis_data:

networks:
  SW_NETWORK: