version: '3.8'
services:
  db:
    image: postgres:16
    container_name: storywink_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: storywink
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - storywink_network

volumes:
  postgres_data:

networks:
  storywink_network: 